### ISSUE TITLE
|    LArgMain , Don't understand :[ExportFitASTER=1]

### ISSUE THREAD

**Issue by deepak-shah-np** [luc-girod/MMASTER-workflows#1]
I tried to run WorkFlowASTER_onescene.sh and WorkFlowASTER_onestrip.sh .
Both are throwing following error : 

Error : 
` KIND OF ERR : User's error
|   Sorry, the following FATAL ERROR happened
|
|    LArgMain , Don't understand :[ExportFitASTER=1]`

And after this :
`------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened
|
|    GetSec::Sec
|
------------------------------------------------------------`
`-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 93
|          of file : /home/kshakya/micmacdir/micmac/include/../src/uti_phgrm/MICMAC/uti_MICMAC.h
-------------------------------------------------------------`
And,

`------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened
|
|    FileLogMM3d: cannot open file for writing in [Ortho-MEC-Malt/../]
|
------------------------------------------------------------`
`-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 71
|          of file : /home/kshakya/micmacdir/micmac/src/CBinaires/mm3d.cpp
-------------------------------------------------------------`
and then,

`------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened
|
|    Unknown command in mm3d
|
------------------------------------------------------------`
`-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 1411
|          of file : /home/kshakya/micmacdir/micmac/src/CBinaires/mm3d.cpp
-------------------------------------------------------------`

and 
`cp: cannot stat 'MEC-MaltZ_Num9_DeZoom1_STD-MALT.tfw': No such file or directory
mv: cannot stat 'TrackAngleMap.tif': No such file or directory
ERROR 4: TrackAngleMap_nonGT.tif: No such file or directory
rm: cannot remove 'TrackAngleMap_nonGT*': No such file or directory
/home/kshakya/micmacdir/mmaster/mmasterworkflow/WorkFlowASTER_onestrip.sh: line 209: cd: Ortho-MEC-Malt: No such file or directory
cp: cannot stat 'Orthophotomosaic.tif': No such file or directory
mv: cannot stat 'Orthophotomosaic.tfw': No such file or directory
ERROR 4: Orthophotomosaic_FullRes.tif: No such file or directory
`

**Comment by luc-girod** [comment]
Hei,
You probably don't have the micmac version from the IncludeAlgLib branch. Can you confirm you MicMac version?

The first errors breaks everything so the other errors just follow through.

**Comment by deepak-shah-np** [comment]
Thank you @luc-girod . I fixed . Now its fine.
