### ISSUE TITLE
ApplyParralaxCor or ApplyParallaxCor

### ISSUE THREAD

**Issue by Poleside** [luc-girod/MMASTER-workflows#14]
I encountered this error when running WorkFlowASTER.sh
I've checked that I'm on the IncludeALGLIB branch
```
For command = ApplyParralaxCor
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    Unknown command in mm3d
|                                                           
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :                                
|                                                            
| Error was detected
|          at line : 1697
|          of file : /home/wqh/Documents/micmac/src/CBinaires/mm3d.cpp
-------------------------------------------------------------
Bye  (press enter)
```
Any idea? Thanks in advance!

**Comment by iamdonovan** [comment]
Did you compile micmac yourself, or use the pre-compiled binary?

**Comment by Poleside** [comment]
Hi!
Thank you for the quick response!
It turns out that I am using pymmaster v0.1, and there is a typo in Line 201 of the WorkFlowASTER.sh file.
I have fixed it just as the master branch did, so now it should work perfectly.
I'm new to Python and all this, I apologize for the trouble, and thanks again!
:)

**Comment by Poleside** [comment]
Hi!
Thank you for the quick response
Turns out the pymmaster I'm using is the

**Comment by xiaojiujiu999** [comment]
> Hi! Thank you for the quick response! It turns out that I am using pymmaster v0.1, and there is a typo in Line 201 of the WorkFlowASTER.sh file. I have fixed it just as the master branch did, so now it should work perfectly. I'm new to Python and all this, I apologize for the trouble, and thanks again! :)

what's the typo? Could you show me? Thanks very much

**Comment by Poleside** [comment]
In the version of Tag v0.1, WorkFlowASTER.sh, line 201.
ApplyParralaxCor should be ApplyParallaxCor

**Comment by xiaojiujiu999** [comment]
> In the version of Tag v0.1, WorkFlowASTER.sh, line 201. ApplyParralaxCor should be ApplyParallaxCor

Thanks very much! I just find it as you say. Thanks for your quick response!
