### ISSUE TITLE
Sorry, the following FATAL ERROR happened. Bad value for bool

### ISSUE THREAD

**Issue by xiaojiujiu999** [luc-girod/MMASTER-workflows#19]
Sorry, I meet the problem as follows, and don't konw why.

For Str=2
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    Bad value for bool
|                                                           
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :                                
|                                                            
| Error was detected
|          at line : 1260
|          of file : /root/jiu/micmac/src/util/xml2cpp.cpp
-------------------------------------------------------------
Bye
/root/anaconda3/envs/aster_dem/bin/WorkFlowASTER.sh: line 201: 95044 Aborted                 (core dumped) mm3d SateLib ApplyParralaxCor $name$Bt GeoI-Px/Px2_Num16_DeZoom1_Geom-Im.tif FitASTER=$fitVersion ExportFitASTER=1 ASTERSceneName=$name
mkdir: cannot create directory ‘ImOrig’: File exists
mv: cannot stat 'AST_L1A_00303142023040523_3B.tif_corrected.tif': No such file or directory
".*AST_L1A_00303142023040523(()|_3N|_3B).tif": 2 matches.
OrientationGrille::InitBinary
OrientationGrille::InitBinary
==============================cAppliMICMAC::VerifEtapes 
------------------------------------------------------------
|   Sorry, the following FATAL ERROR happened               
|                                                           
|    GetSec::Sec
|                                                           
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :                                
|                                                            
| Error was detected
|          at line : 93
|          of file : /root/jiu/micmac/include/../src/uti_phgrm/MICMAC/uti_MICMAC.h
-------------------------------------------------------------
Bye

**Comment by luc-girod** [comment]
Hei,
Looks like you didn't follow the installation instructions. The function as defined in the documentation is only working if you compiled MicMac from the "IncludeALGLIB" branch ( https://github.com/micmacIGN/micmac/tree/IncludeALGLIB ).
